name: Auto Tag on Merge With Main

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed to push tags
  pull-requests: read

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next tag
        id: calculate_next_tag
        run: |
          version="${{ env.latest_tag }}"
          version="${version#v}"  # Remove leading 'v'
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          next_tag="v$major.$minor.$patch"
          echo "Next tag: $next_tag"
          echo "next_tag=$next_tag" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.next_tag }}
          git push origin ${{ env.next_tag }}
