name: DAST Scan

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

jobs:
  dast:
    name: Dynamic App Security Testing (DAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project (if required)
        run: |
          if [ -f package.json ] && grep -q '"build"' package.json; then
            npm run build
          fi

      - name: Start Application in Background
        run: |
          npm start & 
          sleep 15  # Wait for server to fully start

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'  # Change if your app runs on a different port
          docker_name: 'owasp/zap2docker-stable'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-config replacer.full_list(0).description=disable -config replacer.full_list(0).enabled=true'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: report_html.html

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
