name: DAST Scan

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create directories for ZAP
        run: |
          mkdir -p playwright/zap-reports playwright/zap-home
          chmod -R 777 playwright/zap-reports playwright/zap-home

      - name: Run ZAP Active Scan
        run: |
          echo "Starting ZAP Active Scan..."
          docker run -v $(pwd)/playwright/zap-reports:/zap/wrk:rw -v $(pwd)/playwright/zap-home:/zap/.ZAP:rw ghcr.io/zaproxy/zaproxy:stable zap.sh -cmd -quickurl https://your-target-app.com -quickattack -quickout /zap/wrk/report.html
          echo "ZAP Active Scan completed"
          ls -la playwright/zap-reports/

      - name: Check ZAP scan results
        run: |
          echo "=== ZAP Active Scan Results ==="
          ls -la playwright/zap-reports/
          if [ -f playwright/zap-reports/report.html ]; then
            echo "HTML report generated successfully"
          else
            echo "Warning: HTML report not found"
          fi

      - name: Upload ZAP scan reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports-50
          path: playwright/zap-reports/
          if-no-files-found: warn
          retention-days: 30
          compression-level: 6
          overwrite: false
          include-hidden-files: false
