name: Lighthouse KPIs

on:
  push:
    branches: 
      - main
      - staging
  pull_request:
    branches: 
      - main
      - staging


jobs:
    lighthouse:
        environment: Production
        name: Lighthouse
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn build

        - name: Install Puppeteer
          run: yarn add puppeteer lighthouse es-main

        - name: Run puppeteer
          run: node lh-auth.js

        - name: run Lighthouse CI
          run: |
            npm install -g @lhci/cli@0.13.x
            lhci autorun
        env: 
          LHCI_GITHUB_APP_TOKEN : ${{ secrets.LHCI_GITHUB_APP_TOKEN }}