name: Lighthouse KPIs

on:
  push:
    branches: 
      - main
      - staging
  pull_request:
    branches: 
      - main
      - staging


jobs:
    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run Lighthouse
              run: npm run lh -- --output json --output-path ./lighthouse-report.json

            - name: Upload Lighthouse report
              uses: actions/upload-artifact@v2
              with:
                name: lighthouse-report
                path: lighthouse-report.json