name: Testing Some Random Stuff

on:
  push:
    branches: [ ui ]

jobs:
  logging:
      environment:
          name: Production 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: commit_id
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get Current Branch
        id: get_branch
        run: echo "name={name}::{branch} >> $GITHUB_STATE $(echo ${{ github.head_ref || github.ref_name }})"
      - name: Set Environment Type
        id: set_env
        run: |
          BRANCH="${{ steps.get_branch.outputs.branch }}"
          if [ "$BRANCH" == "main" ]; then
            echo "name={env_type}::{production} >> $GITHUB_STATE"
          elif [ "$BRANCH" == "merge-test" ]; then
            echo "name={env_type}::{preview} >> $GITHUB_STATE"
          elif [ "$BRANCH" == "ui" ]; then
            echo "name={env_type}::{development} >> $GITHUB_STATE"
          else
            echo "name={env_type}::{Unknown} >> $GITHUB_STATE"
          fi
      - name: Deploy with Vercel
        id: deploy
        run: |
          DEPLOYMENT_OUTPUT=$(vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --scope=${{ secrets.VERCEL_TEAM_ID }} --json)
          echo "${{DEPLOYMENT_OUTPUT}}"
          echo "vercel_deployment_url=$(echo $DEPLOYMENT_OUTPUT | jq -r '.url')" >> $GITHUB_ENV
          echo "vercel_deployment_status=$(echo $DEPLOYMENT_OUTPUT | jq -r '.readyState')" >> $GITHUB_ENV
      - name: Get current Deployed Branch
        run: echo "Deployed branch: ${{branch}}"
      - name: Get current Deployed Environment
        run: echo "Deployed environment: ${{env_type}}"
      - name: Get current Deployed Commit
        run: echo "${{ steps.commit_id.outputs.sha_short }}"
      - name: Get current Deployed URL
        run: echo "Deployed URL: ${{vercel_deployment_url}}"
      - name: Get current Deployed Status
        run: echo "Deployed Status: ${{vercel_deployment_status}}"