name: Testing Some Random Stuff

on:
  push:
    branches: [ ui ]

jobs:
  logging:
    environment:
      name: Production 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set outputs
      id: commit_id
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Get Current Branch
      id: get_branch
      run: echo "::set-output name=branch::$(echo ${{ github.ref_name }})"
    - name: Set Environment Type
      id: set_env
      run: |
        BRANCH="${{ steps.get_branch.outputs.branch }}"
        if [ "$BRANCH" == "main" ]; then
          echo "::set-output name=env_type::production"
        elif [ "$BRANCH" == "ui" ]; then
          echo "::set-output name=env_type::preview"
        elif [ "$BRANCH" == "staging" ]; then
          echo "::set-output name=env_type::development"
        else
          echo "::set-output name=env_type::unknown"
        fi
    - name: Deploy with Vercel
      run: vercel pull --yes --environment=${{ steps.set_env.outputs.env_type }} --token=${{ secrets.VERCEL_TOKEN }}
    - name: Get Vercel Status
      id: vercel_status
      run: |
        DEPLOYMENT_URL="$(vercel ls --token=${{ secrets.VERCEL_TOKEN }} | jq -r '.[0].url')"
    - name: Get current branch
      run: echo "Current branch is ${{ steps.get_branch.outputs.branch }}"
    - name: Get current environment
      run: echo "Current environment is ${{ steps.set_env.outputs.env_type }}"
    - name: Get commit id
      run: echo "Commit id is ${{ steps.commit_id.outputs.sha_short }}"
    - name: log values
      run: |
        vercel --token=${{ secrets.VERCEL_TOKEN }} logs ${{ steps.set_env.outputs.env_type }}
