name: Testing Some Random Stuff

on:
  push:
    branches: [ ui ]
    # types:
    #   - closed
    # if: github.event.pull_request.merged == true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  logging:
      environment:
          name: Production 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: commit_id
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get Current Branch
        id: get_branch
        run: echo "name={name}::{branch} >> $GITHUB_STATE $(echo ${{ github.head_ref || github.ref_name }})"
      - name: Set Environment Type
        id: set_env
        run: |
          BRANCH="${{ steps.get_branch.outputs.branch }}"
          if [ "$BRANCH" == "main" ]; then
            echo "name={env_type}::{production} >> $GITHUB_STATE"
          elif [ "$BRANCH" == "merge-test" ]; then
            echo "name={env_type}::{preview} >> $GITHUB_STATE"
          elif [ "$BRANCH" == "ui" ]; then
            echo "name={env_type}::{development} >> $GITHUB_STATE"
          else
            echo "name={env_type}::{Unknown} >> $GITHUB_STATE"
          fi
      - name: Deploy with Vercel
        run: vercel pull --yes --environment=${{ steps.set_env.outputs.env_type }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Get current Deployed Branch
        run: echo "${{ steps.get_branch.outputs.branch }}"
      - name: Get current Deployed Environment
        run: echo "${{ steps.set_env.outputs.env_type }}"
      - name: Get current Deployed Commit
        run: echo "${{ steps.commit_id.outputs.sha_short }}"
      - name: Get deployment status
        run: echo "${{ job.status }}"