name: Testing Some Random Stuff

on:
  pull_request:
    branches: [ ui, merge-test ]
    types:
      - closed

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  logging:
      if: github.event.pull_request.merged == true
      environment:
          name: Production 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: commit_id
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get Current Branch
        id: get_branch
        run: echo "name={name}::{branch} >> $GITHUB_STATE $(echo ${{ github.head_ref || github.ref_name }})"
      - name: Set Environment Type
        id: set_env
        run: |
          BRANCH="${{ steps.get_branch.outputs.branch }}"
          if [ "$BRANCH" == "main" ]; then
            echo "name={env_type}::{production} >> $GITHUB_STATE"
          elif [ "$BRANCH" == "merge-test" ]; then
            echo "name={env_type}::{preview} >> $GITHUB_STATE"
          elif [ "$BRANCH" == "staging" ]; then
            echo "name={env_type}::{development} >> $GITHUB_STATE"
          else
            echo "name={env_type}::{Unknown} >> $GITHUB_STATE"
          fi
      - name: Deploy with Vercel
        run: vercel pull --yes --environment=${{ steps.set_env.outputs.env_type }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Current Deployed Branch
        run: echo "name={deployed_branch}::{${{ steps.get_branch.outputs.branch }}" >> $GITHUB_STATE
      - name: Set Deployment URL
        id: set_url
        run: echo "name={deployment_url}::{https://$VERCEL_URL}" >> $GITHUB_STATE
      - name: Set Deployment Status
        id: set_status
        run: echo "name={deployment_status}::{success}" >> $GITHUB_STATE