on:
    push:
      branches: [ ui, merge-test ]
  
jobs:
    logging:
        environment:
          name: Production 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set outputs
          id: commit_id
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        - name: Get Current Branch
          id: get_branch
          run: echo "::set-output name=branch::$(echo ${{ github.ref_name }})"
        - name: Set Environment Type
          id: set_env
          run: |
            BRANCH="${{ steps.get_branch.outputs.branch }}"
            if [ "$BRANCH" == "main" ]; then
              echo "name={env_type}::{production} >> $GITHUB_STATE"
            elif [ "$BRANCH" == "merge-test" ]; then
              echo "name={env_type}::{preview} >> $GITHUB_STATE"
            elif [ "$BRANCH" == "staging" ]; then
              echo "name={env_type}::{development} >> $GITHUB_STATE"
            else
              echo "name={env_type}::{Unknown} >> $GITHUB_STATE"
            fi
        - name: Get current branch
          run: echo "Current branch is ${{ steps.get_branch.outputs.branch }}"
        - name: Get current environment
          run: echo "Current environment is ${{ steps.set_env.outputs.env_type }}"
        - name: Get commit id
          run: echo "Commit id is ${{ steps.commit_id.outputs.sha_short }}"
        - name: Get vercel env
          run: vercel env ls --token=${{ secrets.VERCEL_TOKEN }}