name: Testing Environments Variables And Secrets

on:
  push:
    branches: [ main, staging]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  logging:
    environment:
        name: Production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      id: commit_id
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: write environment
      run: |
        pwd
        ls -la
        touch .env
        echo "CONTENTFUL_SPACE_ID='hdnzteah93de'" >> .env
        echo "CONTENTFUL_ACCESS_TOKEN='Th5r8qPrG8EyTNQX9MoJ5qPDCg-Le05G-E8qE3jijLA'" >> .env
        echo "NEXT_PUBLIC_SPORTSBOOK_URL = https://sports2.monkeytilt.com/en" >> .env
        echo "NEXT_PUBLIC_GAME_LAUNCH_URL = https://gamelaunch.everymatrix.com/Loader/StartInfo/" >> .env
        echo "NEXT_PUBLIC_BASE_URL_V1 = https://monkeytilt.nwacdn.com/" >> .env
        echo "NEXT_PUBLIC_APP_ENV= prod" >> .env
        echo "NEXT_PUBLIC_DOMAIN = 3012" >> .env
      shell: /usr/bin/bash -e {0}
    - name: View env file
      run: cat .env
    - name: List directory
      run: ls -al
    - name: Log the environment secrets
      run: echo "This is vercel secret key ${{ secrets.VERCEL_TOKEN }}"
    - name: Log the environment variables
      run: echo "This is environment type key ${{ vars.ENV_TYPE }} - ${{ vars.NEXT_PUBLIC_APP_ENV }}"
    - name: Log the environment variables
      run: echo "This is environment type key ${{ env.ENV_TYPE }} - ${{ env.NEXT_PUBLIC_APP_ENV }}"
    - name: All github actions
      run: echo "This is the github actions ${{ toJson(github) }}"
    - name: All github events
      run: echo "This is the github events ${{ toJson(github.event) }}"