name: Testing Environments Variables And Secrets

on:
  push:
    branches: [ main, staging]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  logging:
    environment:
        name: Production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      id: commit_id
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: write environment
      working-directory: /
      run: |
        pwd
        ls -la
        touch .env.production
        echo "YOUR_ENV_VARIABLE=value" >> .env.production
      shell: /usr/bin/bash -e {0}
    - name: List directory
      run: ls -al
    - name: Log the environment secrets
      run: echo "This is vercel secret key ${{ secrets.VERCEL_TOKEN }}"
    - name: Log the environment variables
      run: echo "This is environment type key ${{ vars.ENV_TYPE }} - ${{ vars.NEXT_PUBLIC_APP_ENV }}"
    - name: Log the environment variables
      run: echo "This is environment type key ${{ env.ENV_TYPE }} - ${{ env.NEXT_PUBLIC_APP_ENV }}"
    - name: All github actions
      run: echo "This is the github actions ${{ toJson(github) }}"
    - name: All github events
      run: echo "This is the github events ${{ toJson(github.event) }}"